### PR TITLE
Add side padding/margin to various pages

### LINKED ISSUE #53: Improper page padding on donate page on mobile & tablet
### Problem

When on mobile & tablet, the padding is incorrect:

Screen Shot 2023-08-08 at 12 18 45 PM

This is the same problem [we had here in this PR](https://github.com/okTurtles/okturtles.com/pull/51#pullrequestreview-1537657497).

### Solution

Fix the padding, and fix it in a way so that it's fixed on all pages, including the team page (which also has this problem), while making sure that the fix doesn't conflict with [the fix](https://github.com/okTurtles/okturtles.com/pull/51/commits/16a179abd227779c25abfc946a1ef9a4b903adcd) that was applied to the [DPKI page](https://okturtles.org/dpki/). So please generalize this padding across all pages (and DRY the changes on the homepage and [the DPKI page](https://github.com/okTurtles/okturtles.com/pull/51/commits/16a179abd227779c25abfc946a1ef9a4b903adcd) so there is one place to go to adjust the padding for all pages).

### PR DESCRIPTION
**Pull request by SebinSong**
closes #53 

Made sure the issue is fixed in all the pages of the website `/dpki`, `/team`, `/donate`, `/finances`.
(Pls let me know there is a missing page here though)

### CODE REVIEW

**Review by taoeffect — CHANGES_REQUESTED** [review]
It's looking good on mobile and tablet now, great work @SebinSong!

However, it seems like desktop is now no longer working.

On desktop (or when the width is sufficiently large to be considered "desktop"), it needs to look and behave like it currently does on https://okturtles.org:

Screen Shot 2023-08-15 at 9 13 31 AM

But now it behaves as if it were on mobile:

Screen Shot 2023-08-15 at 9 13 22 AM

**Comment by taoeffect** [comment]
@SebinSong replied to your video on Slack! Indeed the problem is visible in it.

**Comment by SebinSong** [comment]
@taoeffect The PR has been updated again with the fix for your change request.

**Review by taoeffect — APPROVED** [review]
Looks good in my quick tests! Thanks @SebinSong - very nicely done!

**Pull request merged**
