### PR TITLE
feat: add a dedicated DPKI page (closes #49)

### LINKED ISSUE #49: Create dedicated DPKI page
### Problem

The DPKI project link on the homepage links to a blog post.

It should link to a dedicated page about DPKI that has more resources (including that blog link).

### Solution

Create a dedicated page for DPKI.

It can be based on the current homepage:

Screen Shot 2023-07-13 at 9 01 42 AM

But it should also include embeds to the following:

- https://www.youtube.com/watch?v=IjbzIV5ElCY
- https://www.youtube.com/watch?v=xAbh0eFWrSw (part 1)
- https://www.youtube.com/watch?v=c94gCECFIOs (part 2)

And link to the blog post as well: https://blog.okturtles.org/2017/02/coniks-vs-key-transparency-vs-certificate-transparency-vs-blockchains/

### PR DESCRIPTION
**Pull request by akhileshthite**
@taoeffect #49 Done.

## Checklist:
- [x] Created a dedicated DPKI page
- [x] Followed the home page theme
- [x] Three youtube video embeds (responsive)
- [x] DPKI blog post link
- [x] Ran prettier on the updated code  

##  Screen recording:
dpki page pull request

Question: what's "DKPI" on the homepage? typo?
Screenshot 2023-07-18 at 10 45 43 PM

### CODE REVIEW

**Comment by taoeffect** [comment]
Awesome PR @akhileshthite!

> Question: what's "DKPI" on the homepage? typo?

Yep! Great catch!! Surprised I didn't notice that myself. 🤦

**Comment by akhileshthite** [comment]
> > Awesome PR @akhileshthite!
> > > Question: what's "DKPI" on the homepage? typo?
> > 
> > 
> > Yep! Great catch!! Surprised I didn't notice that myself. 🤦
> 
> :D I know, it happens to me too!

I fixed it, you can add the banner image later.

**Comment by akhileshthite** [comment]
> Excellent work @akhileshthite!! Thanks for sending this in 😄
> 
> One issue I was able to find relates to how the page header and okTurtles title (and related text) behaves in terms of padding when the page is viewed on mobile.
> 
> It should look either like this (based on current okturtles.org behavior):
> 
> Screen Shot 2023-07-18 at 11 19 41 AM
> 
> Or like this (based on current `master`):
> 
> Screen Shot 2023-07-18 at 11 22 55 AM
> 
> However it looks like this in this PR:
> 
> Screen Shot 2023-07-18 at 11 20 34 AM
> 
> My vote is to make it look like the current okturtles.org (at commit [d384cef](https://github.com/okTurtles/okturtles.com/commit/d384cef963551af3ccfc237203d5cf8b623ff395)).

Done.

https://github.com/okTurtles/okturtles.com/assets/68826419/75daf16b-94de-47f1-ad7f-fc59bd6ebc56

**Review by taoeffect — CHANGES_REQUESTED** [review]
Almost! There is still a width at which the padding is incorrect, related to tablet sizes:

Screen Shot 2023-07-19 at 10 41 31 AM

Also, please make sure to run `npm run compile-sass` once you've fixed it before pushing your changes, as I had to run that manually to be able to see your changes.

**Comment by akhileshthite** [comment]
> Almost! There is still a width at which the padding is incorrect, related to tablet sizes:
> 
> Screen Shot 2023-07-19 at 10 41 31 AM
> 
> Also, please make sure to run `npm run compile-sass` once you've fixed it before pushing your changes, as I had to run that manually to be able to see your changes.

Sorry, my bad. Added padding for tablets, laptops, and large desktops.

https://github.com/okTurtles/okturtles.com/assets/68826419/83b18abb-45e9-4fb7-9abb-2cc39e8c2456

That's strange, I ran `npm run compile-sass`, the file also showed modified indication:
It didn't reflect in the previous commit.
Screenshot 2023-07-20 at 12 00 09 AM

Anyways, all the changes are reflected in the latest commit.

**Review by taoeffect — APPROVED** [review]
Beautifully done @akhileshthite! 👏 

Approved! 😄 🎉  Thank you for sending this in!!!

**Pull request merged**
